### ISSUE TITLE
"Invalid JSON: <host>.<domain>.com unknown error}"

### ISSUE THREAD

**Issue by leandrok** [gilt/ionroller#12] opened 2015-09-18 01:52 UTC
Hi, first of all, congratulations for your project.

I have a problem trying to launch my service and I need your help please. 

When I execute:

      "ionroller set_config <service-name> /path/to/service.json"

I got this error:

      "Invalid JSON: <host>.<domain>.com: unknown error}"  

(<host> and <domain> are displayed with my current host and domain configuration entered on the "url" parameter on the json file)

This error occurs several seconds after execute the "ionroller" command. So, seems like some kind of remote "actions" are performed (when the json file is malformed, an error is immediately displayed, but this is not the case)

I followed all your instructions carefully creating the S3 bucket, the KeyPair, the IAM role, the VPC, the Subnet and the Load Balancer. Also I carefully replaced the values on your sample json file (by the way, seems like the last "}" is missing at https://github.com/gilt/ionroller/blob/master/docs/serviceSetup.md). But I still have that problem.

By the way, I'm not completely sure about what should be the "url" on the json file. It's the url provided by the load balancer? Or should be a special DNS record created on Route 53?

Another question please: I guess that ionroller launch the EC2 instances automatically, right? So, it's ok if -when I create the load balancer- no EC2 instances are assigned to that load balancer (because no instances exists on the VPC yet)?

I also included these questions because maybe the error I'm facing is due some wrong configuration.

Thanks in advance!

Best Regards

**Comment by nataliab** [comment] 2015-09-18 11:12
Could you check if your JSON file is valid using any of the online validators, i.e.  http://jsonlint.com/ ?
Most probably it's a missing comma or closing brace. (I've just fixed the missing closing brace in service setup, thanks for catching this!).

The url should be the DNS entry from Route53. The example url can look like: 

hello-svc.nat.lyranthe.org. 

In this case I created a service called hello-svc in ION-Roller and a new hosted zone with domain 'nat.lyranthe.org' in Route53.

So your url = <SERVICE_NAME>.<DOMAIN>

```json
{
   "url":"hello-svc.nat.lyranthe.org"
}
```
ION-Roller launches instances automatically. When you create your load balancer you don't need to add any EC2 instances to it.

**Comment by nataliab** [comment] 2015-09-18 11:27
There was also a missing closing brace in configuration template at https://github.com/gilt/ionroller/blob/master/docs/deployingServices.md. It's fixed now. Please try to add your service again and let us know if it works fine now! Thanks!

**Comment by leandrok** [comment] 2015-09-18 13:12
Hello Natalia,

Thank you very much for your very useful feedback.

Your information about the url configuration and your confirmation about the instances launch process is useful.

Regarding the json file, I verified that it's valid:

![valid-json](https://cloud.githubusercontent.com/assets/865865/9959823/25e63988-5ded-11e5-9188-7f82ffee9246.png)

As I said, seems like some remote process is performed because I got that error several seconds after execute "ionroller set_config ...".

Any ideas about how can I debug the source of the problem?

Thanks again!

Best Regards

**Comment by nataliab** [comment] 2015-09-20 19:53
You need to move "remove_unused_after_minutes" one level up. It should be at the top level of the JSON configuration (same as "external_elb"). Also I've updated the configuration template in documentation to fix this issue. Apologies for this being confusing!

**Comment by nataliab** [comment] 2015-09-23 10:38
@leandrok did you have chance to verify my last comment?

**Comment by blancsys** [comment] 2015-09-23 11:56
Hi Natalia,

Thank you very much for your template adjustments and extra information.

I tested all the process again from scratch.

When I try to run "ionroller release ionroller 1.0.2 --emergency_deploy" y got this error:

....
Sep 23, 2015 8:43:52 AM com.amazonaws.auth.profile.internal.ProfilesConfigFileLoader onProfileProperty
INFO: Skip unsupported property name region in profile [default].
Exception in thread "main" com.amazonaws.AmazonServiceException: Roles may not be assumed by root accounts. (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: 5daeed1a-61e8-11e5-974c-5f8515bbe0ce)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
        ...

By the way, I see that ION-Roller has created a new Role automatically:

![ionroller-role](https://cloud.githubusercontent.com/assets/14373723/10044376/ce32537e-61d0-11e5-9afd-e3a3c65ba646.png)

I has been Googling about the error ("Roles may not be assumed by root accounts.") but I can't find any useful information. I'm afraid that I'm stuck here.

Any ideas?

Thank you very much!

Best Regards

**Comment by nataliab** [comment] 2015-09-24 12:50
Please check the Trust Relationship for your ionroller role. 
The user (or role) listed there should match the one that you used to generate [AWS Access keys](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration).

![trustrelationships](https://cloud.githubusercontent.com/assets/1488329/10073757/25890d3c-62c3-11e5-899a-bf5fc50c1919.png)

**Comment by leandrok** [comment] 2015-09-24 15:33
Hello Natalia,

Thank you very much for your reply and support.

Until now, I just used my "root" Amazon account to create the ION-Roller setup. And that account have full permissions of course:

![trustrelationship](https://cloud.githubusercontent.com/assets/865865/10077690/d1263248-62b7-11e5-9d48-370d4073a6e3.png)

I know that create a new IAM user is important for a production setup (to enforce permissions restrictions), but I'm just on "development" phase at this moment, trying to have a test working setup as soon and simple as possible.

I followed the steps on AWS described at https://github.com/gilt/ionroller/blob/master/docs/gettingStarted.md but is not clear to me if the use of an IAM user is a requirement or just a "best practice". Have you tested ION-Roller using a "regular" Amazon account? If not, I will create the IAM user.

Thank you very much!

Best Regards

**Comment by nataliab** [comment] 2015-09-27 11:34
@leandrok The exception that you pasted says "Roles may not be assumed by root accounts", and assuming a role is required for ION-Roller setup. Please proceed with IAM user. Mind that you'll have to either 
 - delete ionroller role manually and then run "ionroller setup ..." again to re-create it

or 

 - manually update trust relationship to point to your IAM user.

**Comment by nataliab** [comment] 2015-10-07 17:12
@leandrok Could you let us know if the problem is solved?

**Comment by leandrok** [comment] 2015-10-08 13:20
@nataliab Hello Natalia, thank you very much for your message.

I'm afraid that I still face the same problem. I tried both approaches suggested by you:

1) If I deleted the "ionroller" role on IAM and then executed "ionroller setup" again. The ionroller role is re-created, but it still shows my root account on the "Trust Relationship" section. That's weird because I previously configured (using "aws configure") the AWS keys of my ionroller user (not my root account) and I also configured on the ionroller-config.json file the account "ionroller@543664081663". Is this ok?

2) So, I tried the second approach, manually editing the Trust Relationship as shown on the attached screenshot, replacing "arn:aws:iam::543664081663:root" with "arn:aws:iam::543664081663:user/ionroller". After that, executing "ionroller release ionroller 1.0.2 --emergency_deploy" still shows the error "Roles may not be assumed by root accounts. (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied". I guess it's still reading the old configuration from some place, but I don't know where it is.

![ionroller-](https://cloud.githubusercontent.com/assets/865865/10367331/2dfe6e60-6da6-11e5-8a2d-912be1cf1ef0.png)

Could be possible add to your documentation a brief tutorial indicating how should be created and configured the ionroller user?

Thank you very much.

Best Regards

**Comment by nataliab** [comment] 2015-10-11 18:16
@leandrok You need to create [AWS Access Keys](http://docs.aws.amazon.com/general/latest/gr/getting-aws-sec-creds.html) for this new IAM user 'ionroller'. If you have installed AWS CLI you can later run ```aws configure```and enter access key and secret for your IAM user [(example)](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration). 

To sum up:
   1. ```ionroller setup``` is using AWS credentials set on your machine. The default profile in your AWS credentials has to point to a IAM user (non root role). 
   2. This IAM user needs to be added as a trusted entity for role ionroller.

**Comment by leandrok** [comment] 2015-10-16 21:22
@nataliab Hi Natalia, thank you very much for your information.

Now, I'm facing the following issue. When I execute:

ionroller release ionroller 1.0.2 --emergency_deploy --config=./ionroller-config.json

I got the following error

```
Exception in thread "main" java.lang.RuntimeException: Incorrect format for date.
	at scala.sys.package$.error(package.scala:27)
	at ionroller.cmd.IonrollerParser$$anonfun$cmdAndParams$1.applyOrElse(IonrollerParser.scala:182)
	at ionroller.cmd.IonrollerParser$$anonfun$cmdAndParams$1.applyOrElse(IonrollerParser.scala:181)
	at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:189)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at scalaz.concurrent.Task$$anonfun$handleWith$1.apply(Task.scala:76)
	at scalaz.concurrent.Task$$anonfun$handleWith$1.apply(Task.scala:75)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$.Try(Task.scala:386)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
	at scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
	at scalaz.concurrent.Future.step(Future.scala:110)
	at scalaz.concurrent.Future.listen(Future.scala:75)
	at scalaz.concurrent.Future.runAsync(Future.scala:142)
	at scalaz.concurrent.Future.run(Future.scala:159)
	at scalaz.concurrent.Task.run(Task.scala:96)
	at scalaz.concurrent.TaskApp$class.main(TaskApp.scala:16)
	at ionroller.cmd.Main$.main(Main.scala:34)
	at ionroller.cmd.Main.main(Main.scala)

Could this problem be related to the operating system localization configuration? Or it's a different issue?

Thank you very much again!

**Comment by leandrok** [comment] 2015-10-16 21:46
@nataliab By the way, just FYI, seems like this issue is not related to the regional configuration on my machine. As you can see on the following screenshot, the "date and time" configuration is set to the "United States" localization.

![localization](https://cloud.githubusercontent.com/assets/865865/10554039/0b6cde4a-7436-11e5-8f66-777496914428.png)

Any feedback will be greatly appreciated.

Thank you very much in advance!

**Comment by nataliab** [comment] 2015-10-19 10:35
@leandrok 
```--config``` expects a configuration timestamp (ISO_8601_DATE) as a parameter for deployment and it doesn't work combined with ```--emergency_deploy```

Please follow steps as in the documentation:
1. ```ionroller setup /<PATH_TO_CONFIG>/ionroller-config.json```
2. ```ionroller release ionroller <IONROLLER_VERSION> --emergency_deploy```

**Comment by leandrok** [comment] 2015-10-19 12:18
@nataliab Thank you very much for your reply.

I performed both steps exactly as you have described and I still got this error: 

```
Exception in thread "main" com.amazonaws.AmazonServiceException: Roles may not be assumed by root accounts. (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied;
```

The error message is pretty clear. But that's weird because my ionroller-config.json file doesn't use any Amazon root account now: 

```
"aws_account_id":"ionroller@543664XXXXXX"   (XXXXXX added by me)
```

However, when I run "ionroller setup /path/to/ionroller-config.json" I got the following output:

```
Setting up ION-Roller...
Config table exists.
Events table exists.
State table exists.
Role "ionroller" exists.
Adding access policies to role ionroller
Instance profile "ionroller" exists.
Saving config in table: TimelineConfiguration(ionroller.blancsys.com,Z2X79E0UJHK4ER,None,giltouroboros/ionroller,ionroller@543664XXXXXX,ionroller,List(PortMapping(9000,9000)),List(),List(-Dpidfile.path=/dev/null, -Dionroller.modify-environments-whitelist=ALL, -Dionroller.modify-environments-blacklist=ionroller),Some(0 minutes),EBSConfiguration(ionroller,64bit Amazon Linux 2015.03 v2.0.0 running Docker 1.6.2,List({Namespace: aws:ec2:vpc,OptionName: VPCId,Value: vpc-284d824c}, {Namespace: aws:ec2:vpc,OptionName: Subnets,Value: subnet-69421f42}, {Namespace: aws:ec2:vpc,OptionName: ELBSubnets,Value: subnet-69421f42}, {Namespace: aws:autoscaling:launchconfiguration,OptionName: SecurityGroups,Value: sg-0d88946a}, {Namespace: aws:autoscaling:launchconfiguration,OptionName: InstanceType,Value: t2.micro}, {Namespace: aws:autoscaling:asg,OptionName: MaxSize,Value: 1}, {Namespace: aws:autoscaling:launchconfiguration,OptionName: EC2KeyName,Value: ionroller}),None,None,None,None,None,None,None,None,None),2015-10-19T08:57:46.306-03:00)
```

So, as I said, I'm not using a root account on the json config file (not now). But, since that output shows several "<something> exists" maybe my old configuration was saved/cached somewhere? Maybe I should perform some additional step to "purge" the old configurations?

By the way, "aws configure" is also configured to use the credentials of my ionroller user (not the credentials of my root account)

Thank you very much in advance.

Best Regards,

**Comment by nataliab** [comment] 2015-10-21 21:12
@leandrok 
Please check what's the default AWS profile on your machine. Search for \<HOME>/.aws/credentials or  \<HOME\>/.aws/config. This file is created automatically if you run ```aws configure```. The default access key and secret in this file should be for IAM user. Default profile is named as ```[default]```.

**Comment by nataliab** [comment] 2015-10-27 11:03
@leandrok Also, you can check the ionroller configuration in DynamoDB: 
[AWS](https://console.aws.amazon.com/console) -> DynamoDB -> IonrollerConfig table.

**Comment by blancsys** [comment] 2015-10-27 13:16
@nataliab Thank you very much.

My current issue is "Exception in thread "main" com.amazonaws.AmazonServiceException: User arn:aws:iam::543664081663:user/ionroller is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::ionroller@543664081663:role/ionroller (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: a8ec02b0-7859-11e5-be5b-0d5de8762971)"

I guess that there are a missing security configuration.

Thank you very much.
Best Regards

**Comment by nataliab** [comment] 2015-10-28 15:34
@leandrok things to check:
1. User ionroller should be added as a trusted entity in Trust Relationship for role ionroller.
2. User ionroller should have permissions to assume role: 

AWS -> IAM -> Users -> ionroller -> Permissions 

A policy there should include ``` "sts:*"``` action permission, i.e. :
<pre><code>
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "elasticbeanstalk:*",
        "ec2:*",
         ...
        "iam:*",
       <b> "sts:*"</b>
      ],
      "Resource": "*"
    }
  ]
</code></pre>

**Comment by blancsys** [comment] 2015-10-29 13:31
@nataliab Hi Natalia, thank you very much! 

It's solved, I will close this issue. 

Thank you very much for your help!

**Closed** 2015-10-29 13:32 UTC
